sudo: required
language: php
dist: xenial
install:
  - pip install urllib3[secure]
  - pip install pipenv
  - pip install flake8
services:
  - docker
before_script:
  - pipenv run flake8
script:
  - docker build --tag wptagent .
after_script:
  - docker images
