dist: bionic
sudo: required
language: php

jobs:
  include:
    - name: Build Docker image
      services:
        - docker
      script:
        - docker build --tag wptagent .
      after_script:
        - docker images

    - name: Ubuntu installation test
      script:
        - ./ubuntu_install.sh
        - ./test/ubuntu_install.sh
