sudo: required
language: php
install:
  - pip install --upgrade pip
  - pip install pipenv
  - pip install flake8
  - pip install urllib3[secure]
services:
  - docker
before_script:
  - pipenv run flake8
script:
  - docker build --tag wptagent .
after_script:
  - docker images
