# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: script_chunks.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13script_chunks.proto\"\xb1\x01\n\x11ScriptChunkRecord\x12\x0c\n\x04\x64\x61te\x18\x01 \x02(\x05\x12\x0e\n\x06\x63lient\x18\x02 \x02(\t\x12\x0c\n\x04page\x18\x03 \x02(\t\x12\x14\n\x0cis_root_page\x18\x04 \x01(\x08\x12\x0c\n\x04rank\x18\x06 \x01(\x05\x12\x0b\n\x03url\x18\x07 \x02(\t\x12\x0c\n\x04hash\x18\x08 \x02(\t\x12\x0f\n\x07\x63ontent\x18\t \x02(\t\x12\x12\n\nchunk_type\x18\n \x01(\t\x12\x0c\n\x04size\x18\x0b \x01(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'script_chunks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCRIPTCHUNKRECORD']._serialized_start=24
  _globals['_SCRIPTCHUNKRECORD']._serialized_end=201
# @@protoc_insertion_point(module_scope)
